### PR TITLE
Use HTTPS URLs in the generated json files

### PR DESCRIPTION
**Pull request by mineo**
See http://chatlogs.musicbrainz.org/musicbrainz-devel/2014/2014-07/2014-07-01.html#T10-14-05-273215 - tests don't seem to work but from a quick glance it looks like they don't look at this field anyway.

### CODE REVIEW

**Comment by mineo** [comment]
Ping?

**Comment by ianmcorvidae** [comment]
:shipit:

**Comment by 96187** [comment]
Hmm, do we need to update all the existing files too? Maybe that was why we didn't merge this sooner...

**Comment by mineo** [comment]
I agree, that would be good to do, but I have no idea how to do it (except for possibly putting the IDs of all existing releases with cover art into `cover-art-archive.index` again).

**Pull request merged**
