### PR TITLE
Fix delete and index tests

### PR DESCRIPTION
**Pull request by mineo**
The first two commits are just missing variables and renamed methods.

669c268 and daf7eae both fix the same issue, just at different places because I wasn't sure if the code in lib/ or in t/ was wrong.

### CODE REVIEW

**Comment by mineo** [comment]
Ping?

**Comment by ianmcorvidae** [comment]
I'm not sure I follow what passing `rabbitmq => 0` is accomplishing -- could you clarify? Everything else looks quite reasonable, I just don't know enough to follow that bit.

**Comment by mineo** [comment]
The context needs to be initialized with a value for its `rabbitmq` attribute, but that's only used when declaring exchanges and queues, but the tests don't do that, so I just put a zero in there. I'm not sure if there's another meaningful value to put in there - Net::RabbitFoots documentation doesn't mention if it's safe to use it without calling `load_xml_spec` or `connect` :/

**Comment by mwiencek** [comment]
Argh, sorry, I totally didn't see this pull request until I pushed https://github.com/metabrainz/CAA-indexer/commit/cc539e9db3d1e5a1fb06e6068fcab9d5ff2383a1 and checked here. It looks like we made basically the same changes though.

**Pull request closed without merging**
